### ISSUE TITLE
I want to have a name feature

### ISSUE THREAD

**Issue by AlphaBeta906** [R1DF/Phonebook-2#1]
Umm hey I want to have a custom name

**Comment by R1DF** [comment]
Can you clarify please?

**Comment by AlphaBeta906** [comment]
Well I want somthing else than “GUEST” as the username of the phonebook

**Comment by R1DF** [comment]
GUEST is the default name when a person hasn't signed in. To change it, export a phonebook. It will ask for the username. You can also import a ready made phonebook.
